config/routes.rb
Rails.application.routes.draw do
  root "billboards#index"

  resources :billboards 
  #rails helper instead of: get "/billboards", to: "billboards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  def index
    @billboards = Billboard.all 
  end

  def show
    @billboard = Billboard.find(params[:id])
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
      if @billboard.save
        redirect_to billboards_path
      else
        render :new
              #find this Billboard with this id so I can send it back to @billboard.
    end
  end

  private

  def billboard_params
    params.require(:billboard).permit(:artist, :songs)
  def edit
     @billboard = Billboard.find(params:[id])
  end

  def update 
     @billboard = Billboard.find(params:[id])
  end

  def destroy
     @billboard = Billboard.find(params:[id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboards</h1>

<%= link_to 'New Billboard', new_billboard_path %>
<% if @billboards.empty? %>
<h2>No Billboards</h2>
<% else %>
  <ul>
    <% @billboards.each do |billboard| %>
      <li><%= billboard.name %></li>
    <% end %>
  </ul>
<% end %>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<h1>Billboards#show</h1>
<p>Find me in app/views/billboards/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>